name: lunar_lander_env
channels:
  - conda-forge # For other packages, often has more up-to-date versions
  - pytorch # For PyTorch
  - defaults
dependencies:
  - python=3.12 # Or your preferred Python version, e.g., 3.12
  - pip
  - gymnasium
  - pytorch # Installs PyTorch, will pick CPU or CUDA version based on your system
  - torchvision # Often installed with PyTorch, good to have
  - torchaudio # Often installed with PyTorch, good to have
  - numpy
  - matplotlib
  - box2d-py # For LunarLander environment
  - pygame # Dependency for rendering Box2D environments